// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://enuuzuiwpapbcpglgohh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVudXV6dWl3cGFwYmNwZ2xnb2hoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMyMDMyNDAsImV4cCI6MjA2ODc3OTI0MH0.h_OwrxQfOtTZwqIg6vwqDGQ5Xp5AwtlVzeyr-hAy2Gw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});